apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kcp-pki-bootstrap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-pki-ca
spec:
  isCA: true
  commonName: kcp-pki-ca
  secretName: kcp-pki-ca
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  issuerRef:
    name: kcp-pki-bootstrap
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kcp-pki-ca
spec:
  ca:
    secretName: kcp-pki-ca
