{{- if .Values.kcpFrontProxy.openshiftRoute.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kcp-front-proxy
spec:
  host: {{ .Values.externalHostname }}
  port:
    targetPort: 8443
  tls:
    termination: passthrough
  to:
    kind: Service
    name: kcp-front-proxy
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- if .Values.kcpFrontProxy.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kcp-front-proxy
  annotations:
    {{- toYaml .Values.kcpFrontProxy.ingress.annotations | nindent 4 }}
spec:
  tls:
  - hosts:
      - {{ .Values.externalHostname }}
    {{- if .Values.kcpFrontProxy.ingress.secret }}
    secretName: {{ .Values.kcpFrontProxy.ingress.secret }}
    {{- end }}
  rules:
  - host: {{ .Values.externalHostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kcp-front-proxy
            port:
              number: 8443
{{- end }}
{{- if .Values.kcpFrontProxy.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: kcp-front-proxy
spec:
  gatewayClassName: {{ required "gateway.classname is required" .Values.kcpFrontProxy.gateway.className }}
  listeners:
  - name: tls
    protocol: TLS
    port: 8443
    tls:
      mode: Passthrough
    hostname: {{ .Values.externalHostname }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: kcp-front-proxy
spec:
  parentRefs:
  - kind: Gateway
    name: kcp-front-proxy
  rules:
  - backendRefs:
    - name: kcp-front-proxy
      port: 8443
  hostnames:
  - {{ .Values.externalHostname }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-front-proxy
spec:
  secretName: kcp-front-proxy-cert
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  {{ with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{ end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - server auth
  dnsNames:
    - "{{ .Values.externalHostname }}"
  issuerRef:
    name: {{ .Values.kcpFrontProxy.certificate.issuer }}
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-client-ca
spec:
  isCA: true
  commonName: kcp-client-ca
  secretName: kcp-client-ca
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  issuerRef:
    name: kcp-pki-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kcp-client-issuer
spec:
  ca:
    secretName: kcp-client-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-front-proxy-kcp-client-cert
spec:
  secretName: kcp-front-proxy-kcp-client-cert
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  {{ with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{ end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - client auth
  dnsNames:
    - "kcp-front-proxy"
  issuerRef:
    name: kcp-requestheader-client-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert-for-kubeconfig
spec:
  secretName: client-cert-for-kubeconfig
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  commonName: kcp-front-proxy
  subject:
    organizations:
      - "system:masters"
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - client auth
  issuerRef:
    name: kcp-server-client-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-service-account-signing-ca
spec:
  isCA: true
  commonName: kcp-service-account-signing-ca
  secretName: kcp-service-account-signing-ca
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  issuerRef:
    name: kcp-pki-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kcp-service-account-issuer
spec:
  ca:
    secretName: kcp-service-account-signing-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-service-account-cert
spec:
  commonName: kcp-service-account-cert
  secretName: kcp-service-account-cert
  issuerRef:
    name: kcp-service-account-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-front-proxy-virtual-workspaces-client-cert
spec:
  secretName: kcp-front-proxy-virtual-workspaces-client-cert
  duration: 8760h0m0s # 365d
  renewBefore: 360h0m0s # 15d
  {{ with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{ end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - client auth
  dnsNames:
    - "kcp-front-proxy"
  issuerRef:
    name: kcp-requestheader-client-issuer
---
apiVersion: v1
kind: Service
metadata:
  name: kcp-front-proxy
  {{- with .Values.kcpFrontProxy.service.annotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.kcpFrontProxy.service.type }}
  ports:
    - protocol: TCP
      name: kcp-front-proxy
      port: 8443
      targetPort: 8443
  selector:
    app: kcp-front-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kcp-front-proxy-config
data:
  path-mapping.yaml: |
    - path: /
      backend: https://kcp:6443
      backend_server_ca: /etc/kcp/tls/ca.crt
      proxy_client_cert: /etc/kcp-front-proxy/requestheader-client/tls/kcp/tls.crt
      proxy_client_key: /etc/kcp-front-proxy/requestheader-client/tls/kcp/tls.key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcp-front-proxy
  labels:
    app: kcp-front-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcp-front-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kcp-front-proxy
    spec:
      {{- with .Values.kcpFrontProxy.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.kcpFrontProxy.hostAliases.enabled }}
      hostAliases:
        {{- toYaml .Values.kcpFrontProxy.hostAliases.values | nindent 6 }}
      {{- end }}
      containers:
      - name: kcp-front-proxy
        image: {{ .Values.kcpFrontProxy.image }}:{{ .Values.kcpFrontProxy.tag }}
        imagePullPolicy: {{ .Values.kcpFrontProxy.pullPolicy }}
        ports:
        - containerPort: 8443
        command: ["/kcp-front-proxy"]
        args:
        - --secure-port=8443
        - --root-kubeconfig=/etc/kcp-front-proxy/kubeconfig/root-shard.kubeconfig
        {{- if .Values.kcpFrontProxy.shardsKubeConfigFlag }}
        - --shards-kubeconfig=/etc/kcp-front-proxy/kubeconfig/root-shard.kubeconfig
        {{- end }}
        - --tls-private-key-file=/etc/kcp-front-proxy/tls/tls.key
        - --tls-cert-file=/etc/kcp-front-proxy/tls/tls.crt
        - --client-ca-file=/etc/kcp-front-proxy/client/tls/ca.crt
        - --service-account-key-file=/etc/kcp/tls/service-account/tls.key
        - --mapping-file=/etc/kcp-front-proxy/config/path-mapping.yaml
        - --v={{ .Values.kcpFrontProxy.v }}
        - --logging-format=json
        {{- if .Values.kcpFrontProxy.profiling.enabled }}
        - --profiler-address=localhost:{{- .Values.kcpFrontProxy.profiling.port -}}
        {{- end }}
        {{- if .Values.oidc.enabled }}
        - --oidc-issuer-url={{ .Values.oidc.issuerUrl }}
        - --oidc-client-id={{ .Values.oidc.clientId }}
        - --oidc-groups-claim={{ .Values.oidc.groupClaim }}
        - --oidc-username-claim={{ .Values.oidc.usernameClaim }}
        - '--oidc-username-prefix={{ .Values.oidc.usernamePrefix }}'
        - '--oidc-groups-prefix={{ .Values.oidc.groupsPrefix }}'
        {{- if .Values.oidc.caSecretName }}
        - --oidc-ca-file=/etc/kcp/tls/oidc/ca.crt
        {{- end }}
        {{- end }}
        {{- if .Values.kcp.tokenAuth.enabled }}
        - --token-auth-file=/etc/kcp/token-auth/{{ .Values.kcp.tokenAuth.fileName }}
        {{- end }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: livez
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: readyz
            port: 8443
            scheme: HTTPS
        {{- with .Values.kcpFrontProxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: kcp-front-proxy-cert
          mountPath: /etc/kcp-front-proxy/tls
        - name: kcp-front-proxy-config
          mountPath: /etc/kcp-front-proxy/config
        - name: client-cert-for-kubeconfig
          mountPath: /etc/kcp-front-proxy/client-cert-for-kubeconfig
        - name: proxy-kcp-kubeconfig
          mountPath: /etc/kcp-front-proxy/kubeconfig
        - name: kcp-client-ca
          mountPath: /etc/kcp-front-proxy/client/tls
        - name: kcp-ca
          mountPath: /etc/kcp/tls
        - name: kcp-virtual-workspaces-ca
          mountPath: /etc/virtual-workspaces/tls
        - name: kcp-front-proxy-kcp-client-cert
          mountPath: /etc/kcp-front-proxy/requestheader-client/tls/kcp
        - name: kcp-front-proxy-virtual-workspaces-client-cert
          mountPath: /etc/kcp-front-proxy/requestheader-client/tls/virtual-workspaces
        - name: kcp-service-account-cert
          mountPath: /etc/kcp/tls/service-account
        {{- if .Values.kcp.tokenAuth.enabled }}
        - name: kcp-token-auth-file
          mountPath: /etc/kcp/token-auth
        {{- end}}
        {{- if .Values.oidc.enabled }}
        {{- if .Values.oidc.caSecretName }}
        - name: oidc-ca
          mountPath: /etc/kcp/tls/oidc
        {{- end }}
        {{- end }}
      volumes:
      - name: kcp-front-proxy-cert
        secret:
          secretName: kcp-front-proxy-cert
      - name: kcp-client-ca
        secret:
          secretName: kcp-client-ca
          items:
            - key: ca.crt
              path: ca.crt
      - name: kcp-ca
        secret:
          secretName: kcp-cert
          items:
            - key: ca.crt
              path: ca.crt
      - name: kcp-virtual-workspaces-ca
        secret:
          secretName: kcp-virtual-workspaces-cert
          items:
            - key: ca.crt
              path: ca.crt
      - name: kcp-front-proxy-kcp-client-cert
        secret:
          secretName: kcp-front-proxy-kcp-client-cert
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
      - name: kcp-front-proxy-virtual-workspaces-client-cert
        secret:
          secretName: kcp-front-proxy-virtual-workspaces-client-cert
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
      - name: client-cert-for-kubeconfig
        secret:
          secretName: client-cert-for-kubeconfig
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
      - name: kcp-service-account-cert
        secret:
          secretName: kcp-service-account-cert
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
      - name: proxy-kcp-kubeconfig
        secret:
          secretName: proxy-kcp-kubeconfig
          items:
            - key: kubeconfig
              path: root-shard.kubeconfig
      - name: kcp-front-proxy-config
        configMap:
          name: kcp-front-proxy-config
          items:
            - key: "path-mapping.yaml"
              path: "path-mapping.yaml"
      {{- if .Values.oidc.enabled }}
      {{- if .Values.oidc.caSecretName }}
      - name: oidc-ca
        secret:
          secretName: {{.Values.oidc.caSecretName }}
      {{- end }}
      {{- end }}
      {{- if .Values.kcp.tokenAuth.enabled }}
      - name: kcp-token-auth-file
        secret:
          secretName: kcp-token-auth-file
      {{- end }}
