apiVersion: v2
name: api-syncagent
description: A Kubernetes agent to synchronize APIs and their objects between Kubernetes clusters and kcp.

# version information
version: 0.5.0
appVersion: "v0.5.0"

# optional metadata
type: application
home: https://www.kcp.io/
keywords:
  - kcp
  - kubernetes
  - multitenancy
  - controlplane
sources:
  - https://github.com/kcp-dev/helm-charts
  - https://github.com/kcp-dev/api-syncagent
icon: https://raw.githubusercontent.com/kcp-dev/kcp/main/contrib/logo/blue-green.svg
